import type { TranscriptArtifact, Workspace } from "../types";

export const completedWorkspace: Workspace = {
  id: "source-001",
  status: "completed",
  phase: "completed",
  progress: 100,
  auto_rewrite: true,
  request_url: "https://www.youtube.com/watch?v=video001",
  transcript: {
    id: "source-001",
    request_url: "https://www.youtube.com/watch?v=video001",
    auto_rewrite_requested: true,
    status: "completed",
    stage: "rendering",
    progress: 100,
    source: "manual_caption",
    requested_language: null,
    language: "ja",
    language_confidence: null,
    video: { id: "video001", title: "Tiêu đề video gốc", channel: "Demo channel", duration_seconds: 300, webpage_url: "https://youtube.com/watch?v=video001" },
    artifacts: { txt: "/api/v1/transcript-jobs/source-001/artifacts/txt", srt: "/api/v1/transcript-jobs/source-001/artifacts/srt", json: "/api/v1/transcript-jobs/source-001/artifacts/json" },
    warnings: [],
    error: null,
    cached: false,
    created_at: "2026-07-27T10:00:00Z",
    updated_at: "2026-07-27T10:03:00Z",
  },
  rewrite: {
    id: "rewrite-001",
    transcript_job_id: "source-001",
    status: "completed",
    stage: "rendering",
    progress: 100,
    video: { id: "video001", title: "Tiêu đề video gốc", channel: "Demo channel", duration_seconds: 300, webpage_url: "https://youtube.com/watch?v=video001" },
    language: "ja",
    source_length: 100,
    output_length: 112,
    sections_completed: 1,
    sections_total: 1,
    title: "Tiêu đề SEO mới",
    validation: { passed: true, style_score: 92, coverage_score: 95, language_match: true, tts_ready: true, unsupported_claims: [], missing_points: [], length_ratio: 1.12 },
    artifacts: { txt: "/api/v1/rewrite-jobs/rewrite-001/artifacts/txt" },
    warnings: [],
    error: null,
    cached: false,
    created_at: "2026-07-27T10:03:00Z",
    updated_at: "2026-07-27T10:12:00Z",
  },
  action_required: null,
  created_at: "2026-07-27T10:00:00Z",
  updated_at: "2026-07-27T10:12:00Z",
};

export const manualTranscriptArtifact: TranscriptArtifact = {
  schema_version: 3,
  job_id: "source-001",
  source: "manual_caption",
  language: "ja",
  language_confidence: null,
  video: completedWorkspace.transcript.video!,
  segments: [{ index: 1, start_ms: 0, end_ms: 1200, text: "Nội dung gốc.", words: null }],
  warnings: [],
  reconciliation: null,
};

export const koreanWorkspace: Workspace = {
  ...structuredClone(completedWorkspace),
  id: "korean-001",
  auto_rewrite: false,
  rewrite: null,
  transcript: {
    ...structuredClone(completedWorkspace.transcript),
    id: "korean-001",
    request_url: "https://www.youtube.com/watch?v=aSSO1cy5-08",
    auto_rewrite_requested: false,
    source: "whisper",
    language: "ko",
    language_confidence: 0.9990234375,
    video: { id: "aSSO1cy5-08", title: "한국어 테스트 영상", channel: "복이오는길", duration_seconds: 2605, webpage_url: "https://www.youtube.com/watch?v=aSSO1cy5-08" },
    artifacts: { txt: "/api/v1/transcript-jobs/korean-001/artifacts/txt", srt: "/api/v1/transcript-jobs/korean-001/artifacts/srt", json: "/api/v1/transcript-jobs/korean-001/artifacts/json" },
    warnings: ["KOREAN_AUTO_CAPTION_REPLACED_BY_WHISPER", "KOREAN_TRANSCRIPT_RECONCILED", "KOREAN_RECONCILIATION_UNRESOLVED"],
  },
};

export const koreanTranscriptArtifact: TranscriptArtifact = {
  schema_version: 3,
  job_id: "korean-001",
  source: "whisper",
  language: "ko",
  language_confidence: 0.9990234375,
  video: koreanWorkspace.transcript.video!,
  segments: [
    { index: 1, start_ms: 0, end_ms: 1000, text: "병은", words: [{ start_ms: 0, end_ms: 1000, text: "병은", probability: 0.95 }] },
    { index: 2, start_ms: 1000, end_ms: 2000, text: "그를", words: [{ start_ms: 1000, end_ms: 2000, text: "그를", probability: 0.96 }] },
  ],
  warnings: koreanWorkspace.transcript.warnings,
  reconciliation: {
    strategy: "conservative_consensus",
    alignment_version: "monotonic_char_word_v3",
    reference_source: "youtube_automatic_caption",
    secondary_model: "large-v3",
    alignment_coverage: 0.9813496362792138,
    compared_segments: 503,
    suspicious_segments: 149,
    selected_spans: 149,
    processed_spans: 149,
    selected_windows: 97,
    selected_duration_ms: 582740,
    secondary_windows: 97,
    secondary_duration_ms: 582740,
    corrected_segments: 2,
    corrected_words: 2,
    unresolved_segments: 91,
    skipped_segments: 0,
    items: [
      { segment_index: 333, start_ms: 1700000, end_ms: 1700500, primary_text: "명은", caption_text: "병은", secondary_text: "병은", final_text: "병은", decision: "corrected", triggers: ["low_word_confidence", "caption_disagreement"], word_start: 0, word_end: 1, priority_tier: 1, alignment_coverage: 1, temporal_overlap: 0.695652, primary_probability: 0.6, secondary_mean_probability: 0.95, secondary_min_probability: 0.95, decision_reason: "caption_secondary_consensus", corrected_words: 1 },
      { segment_index: 393, start_ms: 2000000, end_ms: 2000500, primary_text: "글을", caption_text: "그를", secondary_text: "그를", final_text: "그를", decision: "corrected", triggers: ["low_word_confidence", "caption_disagreement"], word_start: 0, word_end: 1, priority_tier: 1, alignment_coverage: 1, temporal_overlap: 0.789474, primary_probability: 0.65, secondary_mean_probability: 0.96, secondary_min_probability: 0.96, decision_reason: "caption_secondary_consensus", corrected_words: 1 },
      { segment_index: 4, start_ms: 11800, end_ms: 12320, primary_text: "맞고", caption_text: "맑고", secondary_text: "맑고", final_text: "맞고", decision: "unresolved", triggers: ["caption_disagreement"], word_start: 2, word_end: 3, priority_tier: 3, alignment_coverage: 1, temporal_overlap: 0.81, primary_probability: 0.94, secondary_mean_probability: 0.91, secondary_min_probability: 0.91, decision_reason: "segment_words_not_reconstructable", corrected_words: 0 },
      { segment_index: 501, start_ms: 2585910, end_ms: 2586250, primary_text: "신의", caption_text: "신", secondary_text: "", final_text: "신의", decision: "unresolved", triggers: ["low_word_confidence", "caption_disagreement"], word_start: 3, word_end: 4, priority_tier: 1, alignment_coverage: 1, temporal_overlap: 0, primary_probability: 0.71, secondary_mean_probability: null, secondary_min_probability: null, decision_reason: "secondary_range_partial_word", corrected_words: 0 },
    ],
  },
};
